User Story 13: Inventory
Mistake91/capstone-project pull request #25
Opened 2023-02-01 17:45 UTC by Mistake91

2023-02-02 11:17 UTC, F-Kirchhoff requested changes
Hey Leif,
your game is getting playable, very cool. I have some suggestions to improve the readability of your code and will prevent a lot of bugs in the future. Have a look!

2023-02-02 11:17 UTC, F-Kirchhoff commented on components/inventory.js
> +  display: grid;
double display grid

2023-02-02 11:17 UTC, F-Kirchhoff commented on components/inventory.js
> +  grid-template-columns: 1fr repeat(4, 20%) 1fr;
you can use fr here entirely: 1fr repeat(4,2fr) 1fr

2023-02-02 11:17 UTC, F-Kirchhoff commented on components/layout.js
> +      {inventoryState === true ? <Inventar inventar={inventar} /> : ""}
You use InventoryButton, so please rename this component and its prop to 'Inventory'

2023-02-02 11:17 UTC, F-Kirchhoff commented on components/smeltery.js
> +          inventar[4].amount++
Please use an object as your inventory instead of an array. Then you can use the named values instead of the index. that makes your code much more readable:
```js
const inventory = {
  coal: {
    amount: 42,
    id: "123"
  },
  iron: {
    amount: 42,
    id: "123",
  },
...
}
```

2023-02-02 11:17 UTC, F-Kirchhoff commented on components/smeltery.js
>          );
You should refactor these operations into functions which a descriptive name. Also the -- and  ++ operations mutate your old state, what we don't want: 
```js
function smelterIron() {
  const updatedInventory = {
   ...inventory, // <- you need to write this function where your state is defined to get access to the inventory state
    coal: {
       ...inventory.coal,
       amount: inventory.coal.amount - 1
    },
    ironore: {
       ...inventory.ironore,
      amount: inventory.ironore.amount -1  
    }
   ....
  }
  setInventory(updatedInventory)
}

2023-02-02 14:31 UTC, Mistake91 commented on components/smeltery.js
>          );
can I write it like

`  function smelterIron() {
    const updatedInventory = {
      ...inventory,
      coal: {
        ...inventory.coal,
        amount: (inventory.coal.amount -= 1),
      },
      ironore: {
        ...inventory.ironore,
        amount: (inventory.ironore.amount -= 1),
      },
      ironingot: {
        ...inventory.ironingot,
        amount: (inventory.ironingot.amount += 1),
      },
    };
    setInventory(updatedInventory);
  }`


because when i dont write the "-=1" the the function doesnt repeat, but it should repeat until i stop working

2023-02-02 14:33 UTC, Mistake91 commented on components/smeltery.js
>          );
can I write it like

 ```
function smelterIron() {
    const updatedInventory = {
      ...inventory,
      coal: {
        ...inventory.coal,
        amount: (inventory.coal.amount -= 1),
      },
      ironore: {
        ...inventory.ironore,
        amount: (inventory.ironore.amount -= 1),
      },
      ironingot: {
        ...inventory.ironingot,
        amount: (inventory.ironingot.amount += 1),
      },
    };
    setInventory(updatedInventory);
  }
```

because when i dont write the "-=1" the the function doesnt repeat, but it should repeat until i stop working

2023-02-02 15:45 UTC, F-Kirchhoff requested changes
Hey Leif, 
this is almost ready to go. Please have a look again how the setState function works, you are using it wrong at the moment.

2023-02-02 15:45 UTC, F-Kirchhoff commented on components/inventory.js
> +    </StyledSection>
A nice, I didn't know you were mapping over your inventory. Great solution!

2023-02-02 15:45 UTC, F-Kirchhoff commented on pages/_app.js
> +        amount: (inventory.ironingot.amount += 1),
please don't use the assginment in these lines, we don't want to set the amount of the old inventory object, only use the old value as a reference: `inventory.coal.amount + 1` instead of `+=`

2023-02-02 15:45 UTC, F-Kirchhoff commented on pages/coalmine.js
> +      setInventory(inventory, (inventory.coal.amount += 1));
the setInventory function only accepts one input. please use it as we have shown it in the session: (and don't use the assignment operator, that mutates the old state)
```
setInventory({
  ...inventory,
  coal: {
    ...inventory.coal,
    amount: invenotory.coal.amount + 1
  }
})
```

2023-02-02 15:45 UTC, F-Kirchhoff commented on pages/goldmine.js
> +      setInventory(inventory, (inventory.goldore.amount += 1));
same here.

2023-02-02 15:45 UTC, F-Kirchhoff commented on pages/ironmine.js
> +      setInventory(inventory, (inventory.ironore.amount += 1));
same here

2023-02-06 09:27 UTC, Long-HaHoang approved these changes
Left you some small comments.
Overall looks good to me.
You did the first useEffect with coach Michael anyway.
The rest of useEffect was more less the same.
👍

2023-02-06 09:27 UTC, Long-HaHoang commented on components/inventory.js
> +const InventoryPlace = styled.section`
A section within a section doesn't seem to have the best a11y.
You can use a `<article>` for your `InventoryPlace`

2023-02-06 09:27 UTC, Long-HaHoang commented on components/layout.js
> +      {inventoryState === true ? <Inventory inventory={inventory} /> : ""}
Just a small thing.
Since your state inventoryState is a boolean you can shorten this operator.
Can not a must. 
```javascript
{inventoryState  ? <Inventory inventory={inventory} /> :  null}
```

You might as well add a text or icon within your button. It's difficult to see at first glance in your preview.

2023-02-06 09:27 UTC, Long-HaHoang commented on components/smeltery.js
> +  }, [material, inventory, smelterGold, smelterIron, stopWorking]);
I was there while coach Michael helped you with the useEffect.
👍

2023-02-06 09:27 UTC, Long-HaHoang commented on pages/coalmine.js
> +
That's more less the same useEffect. LGTM 👍

2023-02-06 09:41 UTC, Mistake91 commented on components/inventory.js
> +const InventoryPlace = styled.section`
hey Long, you are right, i changed it

2023-02-06 09:41 UTC, Mistake91 commented on components/layout.js
> +      {inventoryState === true ? <Inventory inventory={inventory} /> : ""}
and thanks for that, changed that aswell

2023-02-06 12:11 UTC, merged