User Story 14: market
Mistake91/capstone-project pull request #28
Opened 2023-02-07 14:00 UTC by Mistake91

i did some changes and now there are 2 buttons, one for buying and one for selling

2023-02-07 17:16 UTC, shebtastic requested changes
i have noticed that all components in your project are have lowercased filenames.
please update these to conform to conventions.

something for a future refactoring could be, that you might want to take a look at shared code among your pages and components and refactor these into reusable functions. this might be especially interesting for recurring tasks like the resource gathering or buying stuff from your market.

2023-02-07 23:37 UTC, Mistake91 commented on components/buy.js
> +    console.log(amount * 2);
thanks, forget them

2023-02-07 23:37 UTC, Mistake91 commented on components/inventory.js
> +            item.id != 99 && (
changed it, thanks

2023-02-07 23:37 UTC, Mistake91 commented on components/layout.js
> -import { Grid } from "@/components/homeStyles";
yea thats right, moved it :)

2023-02-07 23:45 UTC, Mistake91 commented on components/inventory.js
> +            item.id != 99 && (
and yes, i will create a user story where i will do some refactoring or is it important to do it now? 👀

2023-02-08 10:20 UTC, NikRoe approved these changes
Hi there,

looks good to me

2023-02-08 14:26 UTC, merged